### ISSUE TITLE
JXL manual

### ISSUE THREAD

**Issue by zsiki** [vargiattila/JXL-to-GSI#1]
Is there a JXL description or only the XML schema is available? I couldn't find find any in 5 minutes search on the web.

**Comment by vargiattila** [comment]
On the official Trimble site is mentioned: "A JXL file is an XML representation of the .job file.", but I couldn't find description staff for .job or .jxl files either. 
The calculation formulas are from the "Trimble calculation reference", available in the following link:
https://help.trimblegeospatial.com/TrimbleAccess/latest/en/PDFs/Access-Calculations-Reference.pdf

**Comment by faludiz** [comment]
> Is there a JXL description or only the XML schema is available? I couldn't find find any in 5 minutes search on the web.

https://ww2.trimble.com/schema/JobXML/5_3/JobXMLSchema-5.3.xsd
