### ISSUE TITLE
JXL formátum

### ISSUE THREAD

**Issue by faludiz** [vargiattila/JXL-to-GSI#5]
Szia!

Van egy kis gondom magával a JXL értelemzésével.

A **APT_0321_V3.jxl** fájlban van egy **UnitsRecord**, amiben az **AngleUnit**s értke **DMSDegrees**. Ugye elvileg ez mondja meg, hogy a szögek milyen egységben vannak tárolva.
Nos ez a **DMSDegrees** az én olvasatomban azt jelenti, hogy a szögek **fok.ppmp** (áldedimális) formában vannak megadva, vagyis a sem a **pp** sem az **mp** nem lehet több mint 59. Erre ilyenek vannak benne:

```xml
<HorizontalCircle>28.9641783</HorizontalCircle>
<VerticalCircle>89.75777565</VerticalCircle>
```

Ez nálam inkább a **DecimalDegrees** vagyis f**ok.tizedfok** formátumnak felel meg.

A vonatkozó sémafájlban sincs bő lére eresztve a dolog:
```xsd
  <xsd:simpleType name="angleUnitsType">
    <xsd:annotation>
      <xsd:documentation>Valid angle units (for display) are DMSDegrees, DecimalDegrees, Gons, Mils or QuadrantBearings</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="DMSDegrees"/>
      <xsd:enumeration value="DecimalDegrees"/>
      <xsd:enumeration value="Gons"/>
      <xsd:enumeration value="Mils"/>
      <xsd:enumeration value="QuadrantBearings"/>
    </xsd:restriction>
  </xsd:simpleType>
```

A másik érdekes dolog, hogy vajon miért forgatod össze az álláspontokat és az irányokat miért közepeled? Szerintem elég lenne az egy álláspontonton belül az ugyanarra pontra menő első és második távcsőállás közepelése. Hálózat kiegyenlítéskor ugyanis (a [YASC](https://yasc.hu)-ban legalábbis) így több lehetőséged van/lenne az esetlegesen hibás mérések kizárására. Azzal, hogy mindent közepelsz, azzal az esetlegesen jó mérést is elrontod.
Ennek az összeforgatásnak, közepelésnek nem sok jelentősége van, hiszen nem papíron kell kiszámolgatni, a számítógép könnyedén elboldogul vele.

Csak érdekességképpen a JXL-ből konvertált GSI 13 álláspontot és 55 mért pontot tartalmaz, ha ugyanezt YASC-ba töltöm be, akkor 24 álláspontom és 105 mért pontom lesz:
![image](https://github.com/vargiattila/JXL-to-GSI/assets/89804084/3406e89f-a074-4f8e-9c44-e4429714d5c0)

A JXL betöltés kb most lett kész, a letölthető verzió még nem tartalmazza. Eddig azért nem volt benne, mert ezzel a formátummal még nem találkoztam. Most is véletlenül a [Geodézia](https://www.facebook.com/groups/geodezia/posts/24790469780536816/) csoportban akadtam rá a témára. Több ilyen JXL fájlom nincs is, csak az amit innen letöltöttem. Ha esetleg van még ilyened, akkor feltehetnél még ide néhányat!

**B.Ú.É.K!**

**Comment by vargiattila** [comment]
Szia!

Először is köszönöm szépen az észrevételeket és boldog új évet kívánok én is.

Az általad említett  UnitsRecord résznél, ahol az AngleUnits is található és értéke DMSDegrees, véleményem és tapasztalatom szerint csak a kezelőszoftverben történő megjelenítési beállításokat módosítja. 

A hivatalos schema leírás szerint minden egyes szög-, széllesség- és hosszúság- érték tizedfok formátumban van tárolva.
![image](https://github.com/vargiattila/JXL-to-GSI/assets/101498041/ace737af-edac-486d-809c-236f36388895)

Az összeforgatást a többfordulós mérések feldolgozása érdekében készítettem, mert nem voltam biztos benne, hogy a Geoeasy hogyan kezeli.  Nyilvánvalóan igazad van azzal állítással kapcsolatban, hogy mindent közepelek, akkor az esetlegesen jó mérést is elrontom, viszont másképp a több fordulót nem tudom kezelni.

Minimálisan tisztítom is a mérési jegyzőkönyvet, ahol esetlegesen információ hiány van, és a feldolgozás során nem hasznosítható a mérés, már nem írom ki a GSI-be.  A YASC-os betöltést tesztelni fogom, így pontosan nem tudom megállapítani, hogy mely méréseket hagyom ki. 

Találjunk valamilyen platformot és szívesen küldök még több állományt is.

**Comment by faludiz** [comment]
Tipikusan rám vall: pont a lényeget nem olvastam el a sémafájl elején :D
Itt elérhető vagyok: https://m.me/zoltan.faludi
